### ISSUE TITLE
Add minimal ext_localconf.php together with explanation in tutorial for Backend Layouts being available

### ISSUE THREAD

**Issue by oheil** [TYPO3-Documentation/TYPO3CMS-Tutorial-SitePackage-Code#7]
Just installing the sitepackage source is currently (TYPO3 11) not enough to get it running. The Backend Layouts are not showing up in page properties under Appearance -> Backend Layout.
Doing at root page Resources -> Include static Page TSconfig (from extensions) is necessary but not mentioned in the tutorial.
See 
https://stackoverflow.com/questions/69989370/typo3-11-sitepackage-tutorial-expected-template-file-standard-1-html

Example ext_localconf.php:
```
<?php
defined('TYPO3_MODE') || die();

$boot = function (string $_EXTKEY): void {
        \TYPO3\CMS\Core\Utility\ExtensionManagementUtility::addPageTSConfig('
                <INCLUDE_TYPOSCRIPT: source="FILE:EXT:'.$_EXTKEY.'/Configuration/TsConfig/Page/Page.tsconfig">
        ');
};
$boot('site_package');
unset($boot);
```

**Comment by Alagts** [comment]
Starting with TYPO3 v12 a file called page.tsconfig is automatically loaded therefore the settings in ext_localconf.php are not needed anymore and are outdated. Therefore I close the issue.
