### ISSUE TITLE
Reduce needed changes of name/key in site package tutorial code 

### ISSUE THREAD

**Issue by oheil** [TYPO3-Documentation/TYPO3CMS-Tutorial-SitePackage-Code#8]
To create your own site package theme for a web page one typically starts with the tutorial code.
If you want to change the name/key/path of the tutorial code to something personal for a specific web site there are too many places where you have to edit the code.
Try to reduce the number of explicit strings "site_package", "Site package", ... by changing it to some variable which is set at a single place.

**Comment by Alagts** [comment]
@linawolf Can you answer this question?

**Comment by linawolf** [comment]
The code of this extension is structured for didactict reasons to be used with the site package tutorial. Using variables for the extension key etc would complicate things for beginners. 

This extension is not meant to be used in production.
