### ISSUE TITLE
Site package as composer root package

### ISSUE THREAD

**Issue by buepro** [TYPO3-Documentation/TYPO3CMS-Tutorial-SitePackage-Code#9]
The extension `bootstrap_package` demonstrates how the extension can be used as a site package for development purpose by using it as a composer root package. This approach could as well be used for production sites.

Currently the documentation suggests to place the site package into a directory (e.g. `local_packages`) and complement the composer root configuration with a repository definition and a require entry for the site package.

It would be helpful to note in the documentation that TYPO3 allows to use a site package as a composer root package. This could be accommodated in the "Extension installation" section. Please let me know if I can help with that.

**Comment by linawolf** [comment]
I know, that there have been discussions about using a sitepackage like this, however the idea only works when you have no more then one site in the installation. Also with the new features like site sets this is probably not the way to go. So it would add a lot of new complexity to a not yet ripe issue..

**Comment by Alagts** [comment]
There was no further communication since some months. Therefore I close the issue.
